version: "3.9"
services:
  node:
    build: ./node
    ports:
      - "8080:8080"
    image: "sjure/real-kube-node:latest"
  react:
    build: ./react
    ports:
      - "3000:3000"
    links:
      - node
    image: "sjure/real-kube-react:latest"
