# Sheeps. Worker nodes for a Web Dev cluster
#
# Usage:
#    ansible-playbook --ask-vault DevOps-xxx.yaml
#
---
- name: Cloning MVs. Sheeps for DevOps cluster
  hosts: localhost
  gather_facts: false

# Variables
# --

# encrypted file with ansible-vault with the variable
# {{ ovirt_password }} storing the IaaS ULL password

  vars_files:
    - sjurvault.yaml

# SSH key for the user "ansible" 

  vars:
    ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWvWgJ6lTfRMp3nTYikfhQ8uzFeZy7HUFdIjR9P9LgktGb8nm7K/EeoLUCo725iAGhZ9ynr/Pm0lGQ4cjKtjS6VBB3tXskBX1SGWi5v50QhahAQ+S33cLTdhxS61DKArK8uN6uMIlrvyh5DiwS4brIFDLdlOaROgKm65kWkVUKyqazr4jUcFR4Pwl4aJWT0d/nCK0edqjlmxaaFWfBHnTUv3I6VWodb/rAgCOJPbF1oUIyrrB39NAVAzs9cidmWhsFOffV5mCnXPtRCSldQhIvKOEEg9yCatjYCn4S5VgMaU4Ub7AHdp1r18QwpBjabuerVerJ4+g/fVnC9y7DURWSEnMMvQ0yNG4CWI8WZlrP+oZVPN2B/j9fVawXJtwJX4uZ1UZoeuJVcWnsar2A6LTrFE+FjuVFBLJicAZD1FxYayp6K4JSeaN1M2M+7PG3ZHpCyqLttR1CsAxNHt8OOtTcxhtQ85H5KQZye93AE9YH+KMV94y1tWA0RSgvul7gmxSvkzm5iQ8FoXhWM+qZmXdFHi7+xvgObryWLYxXV6n+80o4H/Vs2GpiSwE1d/awWeKPV9iF80gWyRxgZMKi3rRHZzVCXINBupbmt6IMaXVSYEof0Zl2sJkLDNoXfJANhFBI+G2W03V6skVB9ZKY3OL3r+BD0F3kf7QhU+sCWdTQdQ== sjur@Sjurs-PC
# IaaS user (change vblanco by aluxxx...)

    ovirt_login: alu0101456676@ULL

# Node names to create  (in these case, two "sheeps")

    prefix: DevOps
    nodes:
      - name: LoadBalancer
        ip: 192.168.40.1
        
# Private network profile assigned to each Lab group
# See IaaS ULL portal

    node_nics: 
      - name: nic1
        profile_name: DOC1
      - name: nic2
        profile_name: DOCP2P-4014

# Tasks
# ------

  tasks:
    - name: Login to IaaS
      ovirt_auth:
        url: https://iaas.ull.es/ovirt-engine/api
        insecure: yes
        username: "{{ ovirt_login }}"
        password: "{{ ovirt_password }}"
        headers:
          filter: true

    - name: Create a VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: Cluster-Rojo
        name: "{{ prefix }}-{{ item.name }}"
        cpu_cores: 1
        cpu_sockets: 1
        memory: 1GiB
        template: debian-10-sinred-cloudinit
        nics: "{{ node_nics }}"
        state: present
        wait: yes
      with_items: "{{ nodes }}"
    
    - name: Update VM via cloud-init
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ prefix }}-{{ item.name }}"
        state: running
        cloud_init_nics:
          - nic_name: ens3
            nic_boot_protocol: dhcp
            nic_on_boot: yes
            nic_on_boot: True
          - nic_name: ens4
            nic_boot_protocol: static
            nic_ip_address: "{{ item.ip }}"
            nic_netmask: 255.255.255.0
            nic_gateway: 192.168.40.1
            nic_on_boot: yes
            nic_on_boot: True
        cloud_init:
          host_name: "{{ item.name }}"
          user_name: sjur

# Passwd generated with mkpasswd -m SHA-512 alumno2020
# Clear text password is: asdflkjasdf543 
          root_password: $6$BdTAR1aX$MLc4s6r5ymrwoTXiUjT0ABHPiaLpI0nSm4T9i662s31tA1SdUYJ7bwGjlWAJ/fIiWfQmEE/FWszYBKR/aSn8j1 
          authorized_ssh_keys: "{{ ssh_keys }}"
          custom_script: |
            write_files:
              - path: /etc/sudoers.d/sjur
                permissions: '0644'
                content: |
                  sjur ALL=(ALL) NOPASSWD:ALL
              - path: /tmp/saludos.txt
                permissions: '0644'
                content: |
                  "Que pasa, Oveja"
            runcmd:
              - sed -i '/AllowUsers/c\AllowUsers adminstic usuario soporteiass sjur' /etc/ssh/sshd_config
              - systemctl restart sshd
              - apt update -y
              - apt install apt-transport-https ca-certificates curl gnupg lsb-release -y
              - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              - echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
              - apt update -y
              - apt install docker-ce docker-ce-cli containerd.io -y
              - apt update -y
              - apt install docker-compose -y
              - docker run -d -p 80:80 -p 8080:8080 sjure/devops:nginx
        wait: yes
      with_items: "{{ nodes }}"

    - name: Cleanup IaaS auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent



